<?php

namespace AppBundle\Repository;

/**
 * PosologieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosologieRepository extends \Doctrine\ORM\EntityRepository
{
}
